### ISSUE TITLE
clone 오류

### ISSUE THREAD

**Issue by eohyemin** [TrueKim/CTest#9]
$ git clone https://github.com/TrueKim/CTest/blob/master/gitTest/gitTest/ManagementSystem.c
Cloning into 'ManagementSystem.c'...
fatal: repository 'https://github.com/TrueKim/CTest/blob/master/gitTest/gitTest/ManagementSystem.c/' not found

주소가 잘못되었나요?

**Comment by TrueKim** [comment]
http://github.com/TrueKim/CTest 까지만 하면 될 것 같아요 :)

**Comment by eohyemin** [comment]
감사합니다 @TrueKim
